### ISSUE TITLE
Why not async/await?

### ISSUE THREAD

**Issue by eduardoborges** [jesobreira/advqueue#2]
What difference beetween:

```
await Promise.resolve("foo");
await Promise.resolve("foo");
await Promise.resolve("foo");
await Promise.resolve("foo");
await Promise.resolve("foo");
```

or 

```
Promise.all([
  Promise.resolve("foo"),
  Promise.resolve("foo"),
  Promise.resolve("foo"),
])
```

**Comment by jesobreira** [comment]
In your first example, your promises are executed one by one, with no concurrency. In the second example, your promises are executed concurrently.

With this lib, you can run promises with controlled concurrency. You may set how many promises you'd like to run at the same time, as well as setting what happens if a promise stays in the queue for a specified time. Also, you can define a timeout for the promises to resolve or reject, as well as set the items priority (so if you have a more critical task you want to be executed before the other previously queued tasks, you have this control too).

This is more suitable for CPU intensive tasks as well as throttling requests against a REST server to avoid being banned by the server's rate limiter.
